name = "evo-simulation"
main = "workers-site/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./web"

[build]
command = "npm run build:web"

# Custom domain configuration
[env.production]
name = "evo-simulation"
routes = [
  "evo.tre.systems/*"
]
